// agentglass — self-check for the filter grammar: scriptc build src/features/query/parse.check.ts -o pc && ./pc
// SPDX-License-Identifier: Apache-2.0
import { parse, print, caret } from "./parse.ts";

let bad = 0;
function eq(what: string, got: string, want: string): void { if (got !== want) { bad++; console.log("FAIL " + what + ": got " + JSON.stringify(got) + " want " + JSON.stringify(want)); } }

// [input, canonical or "", error message or "", error column (0-based)]
const CASES: string[][] = [
  ["foo", "text ~ foo", "", "0"],
  ["foo bar", "text ~ foo and text ~ bar", "", "0"],
  ["\"foo bar\"", "text ~ \"foo bar\"", "", "0"],
  ["-foo", "text !~ foo", "", "0"],
  ["not foo", "text !~ foo", "", "0"],
  ["repo is agentglass", "repo is agentglass", "", "0"],
  ["project = agentglass", "repo is agentglass", "", "0"],
  ["h is OpenCode", "harness is opencode", "", "0"],
  ["harness is nope", "", "harness is one of claude, codex, fx, pi, opencode, kiro, gemini — got \"nope\"", "11"],
  ["tool is_one_of Bash Edit", "tool is_one_of Bash Edit", "", "0"],
  ["tool is_one_of Bash Edit cost > 2", "tool is_one_of Bash Edit and cost > 2", "", "0"],
  ["tool is_one_of Bash Edit, foo", "tool is_one_of Bash Edit and text ~ foo", "", "0"],
  ["tool is_one_of Bash \"tool\"", "tool is_one_of Bash \"tool\"", "", "0"],
  ["tool is_not_one_of Read Grep", "tool is_not_one_of Read Grep", "", "0"],
  ["cost > 2", "cost > 2", "", "0"],
  ["cost>2", "cost > 2", "", "0"],
  ["cost >2", "cost > 2", "", "0"],
  ["cost>=2", "cost >= 2", "", "0"],
  ["cost > $0.50", "cost > $0.50", "", "0"],
  ["cost > abc", "", "\"cost\" needs a number (e.g. cost > 2, cost > $0.50), got \"abc\"", "7"],
  ["cost is unknown", "cost is unknown", "", "0"],
  ["not cost > 2", "not cost > 2", "", "0"],
  ["-cost > 2", "not cost > 2", "", "0"],
  ["-cost>2", "not cost > 2", "", "0"],
  ["not tool is Bash", "tool is_not Bash", "", "0"],
  ["tool != Bash", "tool is_not Bash", "", "0"],
  ["model ~ opus", "model ~ opus", "", "0"],
  ["model ~opus", "model ~ opus", "", "0"],
  ["model !~ opus", "model !~ opus", "", "0"],
  ["not model ~ opus", "model !~ opus", "", "0"],
  ["not tool is_one_of Bash Edit", "tool is_not_one_of Bash Edit", "", "0"],
  ["not not tool is Bash", "tool is Bash", "", "0"],
  ["tokens > 40k", "tokens > 40k", "", "0"],
  ["tokens > 1.5M", "tokens > 1.5M", "", "0"],
  ["tokens.in >= 2000", "tokens.in >= 2000", "", "0"],
  ["tokens > lots", "", "\"tokens\" needs a number (e.g. tokens > 40k, tokens > 1.5M), got \"lots\"", "9"],
  ["out > 100KB", "out > 100KB", "", "0"],
  ["out > 1MB", "out > 1MB", "", "0"],
  ["out < 512", "out < 512", "", "0"],
  ["duration > 30s", "duration > 30s", "", "0"],
  ["duration >= 500ms", "duration >= 500ms", "", "0"],
  ["duration > 2m", "duration > 2m", "", "0"],
  ["duration > 1h", "duration > 1h", "", "0"],
  ["duration is unknown", "duration is unknown", "", "0"],
  ["duration > 30", "", "\"duration\" needs a duration (e.g. duration > 30s, duration > 500ms), got \"30\"", "11"],
  ["age < 3d", "age < 3d", "", "0"],
  ["error_rate > 20%", "error_rate > 20%", "", "0"],
  ["error_rate > 0.2", "error_rate > 0.2", "", "0"],
  ["day is today", "day is today", "", "0"],
  ["day is yesterday", "day is yesterday", "", "0"],
  ["day >= -7d", "day >= -7d", "", "0"],
  ["day is 2026-10-01", "day is 2026-10-01", "", "0"],
  ["day is 2026-13-01", "", "\"day\" needs a date (2026-10-01, today, yesterday, -7d), got \"2026-13-01\"", "7"],
  ["day is 2026-02-30", "", "\"day\" needs a date (2026-10-01, today, yesterday, -7d), got \"2026-02-30\"", "7"],
  ["weekday is mo", "weekday is mo", "", "0"],
  ["weekday is_one_of sa su", "weekday is_one_of sa su", "", "0"],
  ["weekday is Friday", "weekday is fr", "", "0"],
  ["hour >= 14", "hour >= 14", "", "0"],
  ["status is error", "status is error", "", "0"],
  ["status IS Unknown", "status is unknown", "", "0"],
  ["status is failed", "", "status is one of ok, error, unknown — got \"failed\"", "10"],
  ["live is true", "live is true", "", "0"],
  ["not live is true", "live is_not true", "", "0"],
  ["subagent is_not false", "subagent is_not false", "", "0"],
  ["live is maybe", "", "\"live\" is true or false, got \"maybe\"", "8"],
  ["live ~ t", "", "\"~\" does not apply to live (bool); use is, is_not", "5"],
  ["state is busy", "state is busy", "", "0"],
  ["event is tool", "event is tool", "", "0"],
  ["agent is \"\"", "agent is \"\"", "", "0"],
  ["ext is ts", "ext is ts", "", "0"],
  ["server is github", "server is github", "", "0"],
  ["program is npm", "program is npm", "", "0"],
  ["command ~ \"npm test\"", "command ~ \"npm test\"", "", "0"],
  ["id ~ 3f2a", "id ~ 3f2a", "", "0"],
  ["file is *.test.ts", "file is *.test.ts", "", "0"],
  ["cwd is \"~/my code\"", "cwd is \"~/my code\"", "", "0"],
  ["title ~ \"say \\\"hi\\\"\"", "title ~ \"say \\\"hi\\\"\"", "", "0"],
  ["tol is Bash", "", "unknown key \"tol\" — did you mean tool?", "0"],
  ["zzzzzz is 1", "", "unknown key \"zzzzzz\"", "0"],
  ["tool > 2", "", "\">\" does not apply to tool (text); use is, is_one_of, ~", "5"],
  ["cost ~ 2", "", "\"~\" does not apply to cost (usd); use is, >, >=, <, <=", "5"],
  ["tool is Bash or tool is Edit", "", "\"or\" is not supported; use is_one_of (tool is_one_of Bash Edit)", "13"],
  ["title ~ \"abc", "", "unterminated quote at column 9", "8"],
  ["tool is", "", "tool is …: needs a value", "5"],
  ["tool is, cost > 2", "", "tool is …: needs a value", "5"],
  ["tool is_one_of cost > 2", "", "tool is_one_of …: needs a value", "5"],
  ["foo not", "", "\"not\" needs a filter after it", "4"],
  ["content is_one_of a b", "", "content is_one_of is not supported; use two content ~ clauses", "8"],
  ["content is x", "", "\"is\" does not apply to content; use ~, !~", "8"],
  ["content ~ \"npm test\"", "content ~ \"npm test\"", "", "0"],
  ["TOOL IS Bash AND cost > 2", "tool is Bash and cost > 2", "", "0"],
  ["tool IS_ONE_OF Bash Edit", "tool is_one_of Bash Edit", "", "0"],
  ["tool IS_NOT Bash", "tool is_not Bash", "", "0"],
  ["model !~ OPUS", "model !~ OPUS", "", "0"],
  ["tool is Bash, cost > 2", "tool is Bash and cost > 2", "", "0"],
  ["foo tool is Bash", "text ~ foo and tool is Bash", "", "0"],
  ["tool", "text ~ \"tool\"", "", "0"],
  ["is", "text ~ \"is\"", "", "0"],
  ["cwd ~ ~/code", "cwd ~ ~/code", "", "0"],
  ["cwd ~/code", "text ~ \"cwd\" and text ~ ~/code", "", "0"],
  ["-x", "text !~ x", "", "0"],
  ["\"-x\"", "text ~ -x", "", "0"],
  ["day.cost > 1 and day.tools >= 3", "day.cost > 1 and day.tools >= 3", "", "0"],
  // a connector joins two filters: a dangling one is a typo, never silently dropped
  ["tool is Bash and", "", "\"and\" needs a filter after it", "13"],
  ["foo AND", "", "\"AND\" needs a filter after it", "4"],
  ["foo,", "", "\",\" needs a filter after it", "3"],
  ["and foo", "", "\"and\" needs a filter before it", "0"],
  ["foo and and bar", "", "\"and\" needs a filter before it", "8"],
  ["tool is Bash, and cost > 2", "", "\"and\" needs a filter before it", "14"],
  ["foo and not", "", "\"not\" needs a filter after it", "8"],
  ["foo \"and\"", "text ~ foo and text ~ \"and\"", "", "0"],
  ["", "", "", "0"],
];
for (const c of CASES) {
  const src = c[0] ?? ""; const want = c[1] ?? ""; const err = c[2] ?? ""; const col = c[3] ?? "0";
  const p = parse(src);
  if (err) { eq("err " + src, p.err ? p.err.msg : "(none: " + print(p.cs) + ")", err); eq("col " + src, String(p.err ? p.err.col : -1), col); continue; }
  eq("parse " + src, p.err ? "ERR " + p.err.msg : print(p.cs), want);
  const again = parse(print(p.cs)); eq("roundtrip " + src, again.err ? "ERR " + again.err.msg : print(again.cs), want);
}
eq("caret", caret("tol is Bash", { msg: "x", col: 0 }), "tol is Bash\n^");
eq("caret col", caret("cost > abc", { msg: "x", col: 7 }), "cost > abc\n       ^");
console.log(bad ? bad + " failed" : "filter grammar: all checks passed (" + String(CASES.length) + " cases)");
if (bad) process.exit(1);
