#!/bin/sh
# writes src/build-info.ts — CI passes AGENTGLASS_VERSION/CHANNEL/COMMIT; local builds derive them from git
set -e
cd "$(dirname "$0")/.."
commit="${AGENTGLASS_COMMIT:-$(git rev-parse HEAD 2>/dev/null || echo unknown)}"
sha8=$(printf %s "$commit" | cut -c1-8)
base=$(git describe --tags --match 'v[0-9]*' --abbrev=0 2>/dev/null | sed 's/^v//' || true); [ -n "$base" ] || base=0.0.0
dirty=""; [ -z "$(git status --porcelain 2>/dev/null)" ] || dirty="-dirty"
channel="${AGENTGLASS_CHANNEL:-local}"
version="${AGENTGLASS_VERSION:-$base-local+$sha8$dirty}"
os=$(uname -s | tr 'A-Z' 'a-z'); case "$(uname -m)" in x86_64|amd64) arch=x64;; aarch64|arm64) arch=arm64;; *) arch=$(uname -m);; esac
date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
cat > src/build-info.ts <<EOT
// generated by scripts/build-info.sh — do not edit, not committed
export const BUILD = { version: "$version", channel: "$channel", commit: "$commit", date: "$date", platform: "$os-$arch" };
EOT
